export class ConstantsData {
  static readonly TokenGenerate = 'TokenGenerate';
  static readonly VideoCall = 'VideoCall';
  static readonly VoiceChat = 'VoiceChat';
  static readonly AudioBasicUsage = 'AudioBasicUsage';
  static readonly VideoBasicUsage = 'VideoBasicUsage';
  static readonly CameraPage = 'CameraPage';
  static readonly SEIPage = 'SEIPage';
  static readonly DataChannelMessagePage = 'DataChannelMessagePage';
  static readonly StreamMonitoringPage = 'StreamMonitoringPage';
  static readonly VoiceChangePage = 'VoiceChangePage';
  static readonly PlayAudioFilesPage = 'PlayAudioFilesPage';
  static readonly ProcessAudioRawDataPage = 'ProcessAudioRawDataPage';
  static readonly ProcessVideoRawDataPage = 'ProcessVideoRawDataPage';
  static readonly CustomAudioCapturePage = 'CustomAudioCapturePage';
  static readonly CustomAudioRenderPage = 'CustomAudioRenderPage';
}
